## Creating a logistic regression to predict absenteeism 

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data_preprocessed = pd.read_csv(r"F:\Udemy casse syudy\Absenteeism_data_preprocessed.csv")

In [3]:
data_preprocessed.head(10)

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   
5         0         0         0         1  2015-07-10                     179   
6         0         0         0         1  2015-07-17                     361   
7         0         0         0         1  2015-07-24                     260   
8         0         0         1         0  2015-07-06                     155   
9         0         0         0         1  2015-07-13                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   
5                51   38                  239.554               31          0   
6                52   28                  239.554               27          0   
7                50   36                  239.554               23          0   
8                12   34                  239.554               25          0   
9                11   37                  239.554               29          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3  
5         0     0                          2            7                4  
6         1     4                          8            7                4  
7         4     0                          4            7                4  
8         2     0                         40            7                0  
9         1     1                          8            7                0

## Create the targets 

In [4]:
# get median 
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Exessive Absenteeism'] = targets

In [8]:
data_preprocessed.head(7)

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   
5         0         0         0         1  2015-07-10                     179   
6         0         0         0         1  2015-07-17                     361   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   
5                51   38                  239.554               31          0   
6                52   28                  239.554               27          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   
5         0     0                          2            7                4   
6         1     4                          8            7                4   

   Exessive Absenteeism  
0                     1  
1                     0  
2                     0  
3                     1  
4                     0  
5                     0  
6                     1

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [11]:
# do two variables have the same memory 
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets = data_with_targets.drop(['Date'], axis = 1)

In [13]:
data_with_targets.head(3)

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   

   Children  Pets  Month Value  Day of the Week  Exessive Absenteeism  
0         2     1            7                1                     1  
1         1     0            7                1                     0  
2         0     0            7                2                     0

In [14]:
unscaled_inputs = data_with_targets.iloc[:,0:14]

## standarize the data 

In [15]:
from sklearn.preprocessing import StandardScaler

absenteesim_scaler = StandardScaler()

E:\Anaconada\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [16]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        # Initializing StandardScaler with the passed arguments
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns 
        self.mean_ = None 
        self.var_ = None
        
    def fit(self, X, y=None):
        # Fitting the scaler to the selected columns
        self.scaler.fit(X[self.columns], y)
        # Storing the mean and variance
        self.mean_ = np.mean(X[self.columns], axis=0)
        self.var_ = np.var(X[self.columns], axis=0)
        return self 
    
    def transform(self, X, y=None):
        # Transforming the selected columns using the fitted scaler
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        # Keeping the columns that were not scaled
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        # Returning the DataFrame with original column order
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [18]:
#columns_to_scale = ['Transportation Expense', 'Age', 'Body Mass Index',
                   # 'Children', 'Pets','Month Value']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [19]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs) 

In [23]:
scaled_inputs

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0   -0.577350 -0.092981 -0.314485  0.821365                1.005844   
1   -0.577350 -0.092981 -0.314485 -1.217485               -1.574681   
2   -0.577350 -0.092981 -0.314485  0.821365               -0.654143   
3    1.732051 -0.092981 -0.314485 -1.217485                0.854936   
4   -0.577350 -0.092981 -0.314485  0.821365                1.005844   
..        ...       ...       ...       ...                     ...   
695  1.732051 -0.092981 -0.314485 -1.217485               -0.654143   
696  1.732051 -0.092981 -0.314485 -1.217485                0.040034   
697  1.732051 -0.092981 -0.314485 -1.217485                1.624567   
698 -0.577350 -0.092981 -0.314485  0.821365                0.190942   
699 -0.577350 -0.092981 -0.314485  0.821365                1.036026   

     Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
0            0.412816 -0.536062                -0.806331         0.767431   
1           -1.141882  2.130803                -0.806331         1.002633   
2            1.426749  0.248310                -0.806331         1.002633   
3           -1.682647  0.405184                -0.806331        -0.643782   
4            0.412816 -0.536062                -0.806331         0.767431   
..                ...       ...                      ...              ...   
695         -0.533522  0.562059                -0.853789        -1.114186   
696         -0.263140 -1.320435                -0.853789        -0.643782   
697         -0.939096 -1.320435                -0.853789        -0.408580   
698         -0.939096 -0.692937                -0.853789        -0.408580   
699          0.074838  0.562059                -0.853789        -0.408580   

     Education  Children      Pets  Month Value  Day of the Week  
0            0  0.880469  0.268487     0.182726        -0.683704  
1            0 -0.019280 -0.589690     0.182726        -0.683704  
2            0 -0.919030 -0.589690     0.182726        -0.007725  
3            0  0.880469 -0.589690     0.182726         0.668253  
4            0  0.880469  0.268487     0.182726         0.668253  
..         ...       ...       ...          ...              ...  
695          1  0.880469 -0.589690    -0.388293        -0.007725  
696          0 -0.019280  1.126663    -0.388293        -0.007725  
697          1 -0.919030 -0.589690    -0.388293         0.668253  
698          1 -0.919030 -0.589690    -0.388293         0.668253  
699          0 -0.019280  0.268487    -0.388293         0.668253  

[700 rows x 14 columns]

## Split the data into train and test and shuffle 

In [24]:
from sklearn.model_selection import train_test_split 

In [25]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [26]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)


In [27]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


## Logistic regression with sklearn 

In [28]:
from sklearn.linear_model import LogisticRegression 
from sklearn import metrics 

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train, y_train)

LogisticRegression()

In [31]:
reg.score(x_train,y_train)

0.7839285714285714

In [32]:
reg.intercept_

array([-0.1669092])

In [33]:
reg.coef_

array([[ 2.07452606,  0.33355827,  1.55923   ,  1.32893272,  0.70486037,
        -0.03682454, -0.19993103, -0.00319661,  0.3227044 , -0.3323036 ,
         0.38398576, -0.33216428,  0.18893894, -0.07135387]])

In [34]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [35]:
feature_name = unscaled_inputs.columns.values

In [36]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  coefficient
0                  reason_1     2.074526
1                  reason_2     0.333558
2                  reason_3     1.559230
3                  reason_4     1.328933
4    Transportation Expense     0.704860
5          Distance to Work    -0.036825
6                       Age    -0.199931
7   Daily Work Load Average    -0.003197
8           Body Mass Index     0.322704
9                 Education    -0.332304
10                 Children     0.383986
11                     Pets    -0.332164
12              Month Value     0.188939
13          Day of the Week    -0.071354

In [37]:
summary_table.index = summary_table.index + 1 
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table 

Feature name  coefficient
0                 Intercept    -0.166909
1                  reason_1     2.074526
2                  reason_2     0.333558
3                  reason_3     1.559230
4                  reason_4     1.328933
5    Transportation Expense     0.704860
6          Distance to Work    -0.036825
7                       Age    -0.199931
8   Daily Work Load Average    -0.003197
9           Body Mass Index     0.322704
10                Education    -0.332304
11                 Children     0.383986
12                     Pets    -0.332164
13              Month Value     0.188939
14          Day of the Week    -0.071354

## Interpreting the coafficients 

In [38]:
summary_table['Odds_ratio'] = np.exp(summary_table.coefficient)

In [39]:
summary_table 

Feature name  coefficient  Odds_ratio
0                 Intercept    -0.166909    0.846276
1                  reason_1     2.074526    7.960773
2                  reason_2     0.333558    1.395926
3                  reason_3     1.559230    4.755158
4                  reason_4     1.328933    3.777010
5    Transportation Expense     0.704860    2.023564
6          Distance to Work    -0.036825    0.963845
7                       Age    -0.199931    0.818787
8   Daily Work Load Average    -0.003197    0.996808
9           Body Mass Index     0.322704    1.380857
10                Education    -0.332304    0.717270
11                 Children     0.383986    1.468125
12                     Pets    -0.332164    0.717369
13              Month Value     0.188939    1.207967
14          Day of the Week    -0.071354    0.931132

In [40]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  coefficient  Odds_ratio
1                  reason_1     2.074526    7.960773
3                  reason_3     1.559230    4.755158
4                  reason_4     1.328933    3.777010
5    Transportation Expense     0.704860    2.023564
11                 Children     0.383986    1.468125
2                  reason_2     0.333558    1.395926
9           Body Mass Index     0.322704    1.380857
13              Month Value     0.188939    1.207967
8   Daily Work Load Average    -0.003197    0.996808
6          Distance to Work    -0.036825    0.963845
14          Day of the Week    -0.071354    0.931132
0                 Intercept    -0.166909    0.846276
7                       Age    -0.199931    0.818787
12                     Pets    -0.332164    0.717369
10                Education    -0.332304    0.717270

## testing the model 

In [41]:
reg.score(x_test,y_test)

0.7357142857142858

In [42]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73818406, 0.26181594],
       [0.58978443, 0.41021557],
       [0.36634007, 0.63365993],
       [0.81220479, 0.18779521],
       [0.06146199, 0.93853801],
       [0.30790074, 0.69209926],
       [0.29670107, 0.70329893],
       [0.08157059, 0.91842941],
       [0.80560765, 0.19439235],
       [0.76015779, 0.23984221],
       [0.46268566, 0.53731434],
       [0.15612304, 0.84387696],
       [0.04645643, 0.95354357],
       [0.72518161, 0.27481839],
       [0.23401317, 0.76598683],
       [0.54800338, 0.45199662],
       [0.52970199, 0.47029801],
       [0.55485413, 0.44514587],
       [0.38448275, 0.61551725],
       [0.0254313 , 0.9745687 ],
       [0.69717166, 0.30282834],
       [0.80473679, 0.19526321],
       [0.37908634, 0.62091366],
       [0.40204277, 0.59795723],
       [0.18482564, 0.81517436],
       [0.76088002, 0.23911998],
       [0.47365773, 0.52634227],
       [0.88833741, 0.11166259],
       [0.13622021, 0.86377979],
       [0.79704602, 0.20295398],
       [0.

In [43]:
predicted_proba.shape

(140, 2)

## Save model 

In [44]:
import pickle

In [45]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [46]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)