## Import the relevant libraries 

In [1]:
import numpy as np 

## Declaring scalars, vectors, and matrices 

### Scalars 

In [2]:
n = 5

In [3]:
n

5

### Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

### Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data Types

In [8]:
type(n)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

## Data Shapes 

In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

In [13]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [14]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

## Transposing matrices 

In [15]:
A = np.array([[5,12,6],[-3,0,14]])
A


array([[ 5, 12,  6],
       [-3,  0, 14]])

In [16]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

## Dot product 

In [17]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [18]:
np.dot(x,y)

-66